name: Deploy B2B BUYER to Server

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: b2b-buyer
  ENV_FILE: BASE_URL=api.vasit.uz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Creating .env file
        run: |
          touch .env 
          echo ${{ env.ENV_FILE }} > .env
          cat .env

      - name: Build Docker B2B Buyer image
        run: docker build --rm --no-cache -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker B2B Buyer image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }} ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:$GITHUB_RUN_ID
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:$GITHUB_RUN_ID

      - name: SSH into server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_RUN_ID
          script: |
            helm upgrade --install b2b-buyer /home/helm/helm_charts/b2b-buyer/ -f /home/helm/helm_charts/b2b-buyer/values.yaml --set image.tag=$GITHUB_RUN_ID
